Arboresecense Admin  + supprimer images (admin)
WildCodeSchool/orleans-0917-penduick pull request #9
Opened 2017-10-26 15:30 UTC by Kypli

L'index a été mis a jour ainsi que la création d'un AdminController et tout ses liens d'aministrateur

2017-10-26 16:08 UTC, sblondeau requested changes
a faire (dans une prochaine PR, et chacun pour ses fichiers) : mettre en place le system de template twig avec le base.html.twig

2017-10-26 16:08 UTC, sblondeau commented on src/Controller/AdminController.php
> +            $_FILES['upload']['name'] = strtr($_FILES['upload']['name'], 'ÁÀÂÄÃÅÇÉÈÊËÍÏÎÌÑÓÒÔÖÕÚÙÛÜÝ', 'AAAAAACEEEEEIIIINOOOOOUUUUY', 'áàâäãåçéèêëíìîïñóòôöõúùûüýÿ', 'aaaaaaceeeeiiiinooooouuuuyy');
pas utile si tu fais un uniqueId tout simple à la fin, pas besoin de le concatener avec le [upload][name] de base

2017-10-26 16:08 UTC, sblondeau commented on src/Controller/AdminController.php
> +            } elseif ($_FILES['upload']['size'] >= 5000000)  {
mettre 1000000 car de toute facon le php.ini bloque au dessus par défaut à 2Mo; et 1Mo pour des images web c'est largement suffisant, (meme 200Ko), après c'est beaucoup  trop lourd à charger

2017-10-27 07:38 UTC, sblondeau requested changes

2017-10-27 07:38 UTC, sblondeau commented on src/Controller/AdminController.php
> +             unlink('pictures/upload/' . $fullName);
pb d'indentation
de plus, quand on unlink, c'est tjs bien de faire un file_exists('monchemin/fichier') avant pour vérifier que le fichier qu'on veut effacer existe bien

2017-10-27 07:38 UTC, sblondeau commented on src/Controller/AdminController.php
> +            $extension_upload = strtolower(substr(strrchr($_FILES['upload']['name'], '.'), 1));
il faut plutot utiliser pathinfo pour recup l'extension, ça prend en compte quelques cas tordus d'encodages particuliers.
http://php.net/manual/en/function.pathinfo.php

2017-10-27 07:38 UTC, sblondeau commented on src/Controller/AdminController.php
> +            } elseif ($_FILES['upload']['size'] >= 1000000)  {
le max size peut etre mis en constante de classe pour que ce soit plus facile à modifier

2017-10-27 07:38 UTC, sblondeau commented on src/View/Admin/addPicture.html.twig
> +        <input type="file" name="upload">
là j'ai typiquement plusieurs US dans une seule et du coup pour moi ce form n'est pas terminé car pas mis en page. Pas de label, pas de classes bootstrap...
une US finie comprend aussi la partie front ! 
du coup... on fait comment ?

2017-10-27 07:38 UTC, sblondeau commented on src/View/Admin/deletePicture.html.twig
> +                     style="width:300px"/>
pas de style en inline, utiliser des classes

2017-10-27 07:38 UTC, sblondeau commented on src/View/Admin/deletePicture.html.twig
> +                    <input type="text" name="delete" value="{{ picture.id }}" style="display:none">
pareil style inline a virer partout

2017-10-27 11:26 UTC, Kypli commented
Tes remarques ont été prises en compte. Pour la mise en forme via boostrap de l'add/delete picture, c'est une US qui est en cours. Je sais que c'est pas la bonne méthode, je l'ai bien compris mais c'était le plus simple sur le moment et on ne laissera pas un travail non terminé.

2017-10-27 12:36 UTC, sblondeau approved these changes

2017-10-27 12:36 UTC, sblondeau commented on src/View/Admin/deleteMenu.html.twig
> +        <div class="rowP">
rowP ?

2017-10-27 12:37 UTC, merged